Refactored Delete feature
Pegasusx10/Student-Enrollment-API pull request #4
Opened 2022-10-18 07:06 UTC by Pegasusx10

2022-10-18 11:07 UTC, nandini-vel requested changes

2022-10-18 11:07 UTC, nandini-vel commented on students.js
> +//   const options = {new: true};
@Pegasusx10 commented code should not be merged to develop

2022-10-18 11:07 UTC, nandini-vel commented on students.js
>  async function getstudent(req, res, next) {
getStudent

2022-10-18 11:07 UTC, nandini-vel commented on server.js
>  mongoose.connect('mongodb+srv://Pegasusx10:pegasus123@cluster0.749smlf.mongodb.net/student-database?retryWrites=true&w=majority', { useUnifiedTopology: true, useNewUrlParser: true })
urls should not be hardcoded. They should be picked from an environment config file. database connection should be done separately and that connection should be reused in all files

2022-10-18 13:01 UTC, adarshajit requested changes

2022-10-26 17:33 UTC, adarshajit requested changes

2022-10-27 18:23 UTC, adarshajit requested changes

2022-11-21 10:43 UTC, nandini-vel commented on server.js
> +const connection = require('./config/dbconnection')
dbConnection

2022-11-21 10:43 UTC, nandini-vel commented on students.js
> +const pageSize = parseInt(req.query.pageSize) || 0
fix alignment

2022-11-21 10:49 UTC, adarshajit reviewed
Hi @Pegasusx10, Please take a look and make the neccessary changes

2022-12-07 18:25 UTC, merged